const n=JSON.parse(`{"key":"v-5ae1580f","path":"/dft-learning/pages/fa5420/","title":"numpy 在 win2004 及以上报错","lang":"zh-CN","frontmatter":{"title":"numpy 在 win2004 及以上报错","date":"2020-11-13T17:28:10.000Z","permalink":"/dft-learning/pages/fa5420/","category":["Others"],"updated":"2022-01-17T14:49:18.000Z","description":"在 Windows 20H2 上运行 ASE 报错 ase --version ** On entry to DGEBAL parameter number 3 had an illegal value ** On entry to DGEHRD parameter number 2 had an illegal value ** On entry to DORGHR DORGQR parameter number 2 had an illegal value ** On entry to DHSEQR parameter number 4 had an illegal value Traceback (most recent call last): File \\"c:\\\\users\\\\northword\\\\appdata\\\\local\\\\programs\\\\python\\\\python39\\\\lib\\\\runpy.py\\", line 197, in _run_module_as_main return _run_code(code, main_globals, None, File \\"c:\\\\users\\\\northword\\\\appdata\\\\local\\\\programs\\\\python\\\\python39\\\\lib\\\\runpy.py\\", line 87, in _run_code exec(code, run_globals) File \\"C:\\\\Users\\\\Northword\\\\AppData\\\\Roaming\\\\Python\\\\Python39\\\\Scripts\\\\ase.exe\\\\__main__.py\\", line 4, in &lt;module&gt; File \\"C:\\\\Users\\\\Northword\\\\AppData\\\\Roaming\\\\Python\\\\Python39\\\\site-packages\\\\ase\\\\__init__.py\\", line 8, in &lt;module&gt; import numpy as np File \\"C:\\\\Users\\\\Northword\\\\AppData\\\\Roaming\\\\Python\\\\Python39\\\\site-packages\\\\numpy\\\\__init__.py\\", line 305, in &lt;module&gt; _win_os_check() File \\"C:\\\\Users\\\\Northword\\\\AppData\\\\Roaming\\\\Python\\\\Python39\\\\site-packages\\\\numpy\\\\__init__.py\\", line 302, in _win_os_check raise RuntimeError(msg.format(__file__)) from None RuntimeError: The current Numpy installation ('C:\\\\\\\\Users\\\\\\\\Northword\\\\\\\\AppData\\\\\\\\Roaming\\\\\\\\Python\\\\\\\\Python39\\\\\\\\site-packages\\\\\\\\numpy\\\\\\\\__init__.py') fails to pass a sanity check due to a bug in the windows runtime. See this issue for more information: https://tinyurl.com/y3dm3h86","head":[["script",{"type":"text/javascript"},"var _hmt = _hmt || []"],["script",{"src":"https://hm.baidu.com/hm.js?5574297d56b065f5137cf3654e3de360"}],["script",{"src":"https://hm.baidu.com/hm.js?92a8f6d9fbb75efa90964afcd42be758"}],["meta",{"property":"og:url","content":"https://northword.cn/dft-learning/pages/fa5420/"}],["meta",{"property":"og:site_name","content":"北辞"}],["meta",{"property":"og:title","content":"numpy 在 win2004 及以上报错"}],["meta",{"property":"og:description","content":"在 Windows 20H2 上运行 ASE 报错 ase --version ** On entry to DGEBAL parameter number 3 had an illegal value ** On entry to DGEHRD parameter number 2 had an illegal value ** On entry to DORGHR DORGQR parameter number 2 had an illegal value ** On entry to DHSEQR parameter number 4 had an illegal value Traceback (most recent call last): File \\"c:\\\\users\\\\northword\\\\appdata\\\\local\\\\programs\\\\python\\\\python39\\\\lib\\\\runpy.py\\", line 197, in _run_module_as_main return _run_code(code, main_globals, None, File \\"c:\\\\users\\\\northword\\\\appdata\\\\local\\\\programs\\\\python\\\\python39\\\\lib\\\\runpy.py\\", line 87, in _run_code exec(code, run_globals) File \\"C:\\\\Users\\\\Northword\\\\AppData\\\\Roaming\\\\Python\\\\Python39\\\\Scripts\\\\ase.exe\\\\__main__.py\\", line 4, in &lt;module&gt; File \\"C:\\\\Users\\\\Northword\\\\AppData\\\\Roaming\\\\Python\\\\Python39\\\\site-packages\\\\ase\\\\__init__.py\\", line 8, in &lt;module&gt; import numpy as np File \\"C:\\\\Users\\\\Northword\\\\AppData\\\\Roaming\\\\Python\\\\Python39\\\\site-packages\\\\numpy\\\\__init__.py\\", line 305, in &lt;module&gt; _win_os_check() File \\"C:\\\\Users\\\\Northword\\\\AppData\\\\Roaming\\\\Python\\\\Python39\\\\site-packages\\\\numpy\\\\__init__.py\\", line 302, in _win_os_check raise RuntimeError(msg.format(__file__)) from None RuntimeError: The current Numpy installation ('C:\\\\\\\\Users\\\\\\\\Northword\\\\\\\\AppData\\\\\\\\Roaming\\\\\\\\Python\\\\\\\\Python39\\\\\\\\site-packages\\\\\\\\numpy\\\\\\\\__init__.py') fails to pass a sanity check due to a bug in the windows runtime. See this issue for more information: https://tinyurl.com/y3dm3h86"}],["meta",{"property":"og:type","content":"article"}],["meta",{"property":"og:locale","content":"zh-CN"}],["meta",{"property":"og:updated_time","content":"2022-09-12T09:20:16.000Z"}],["meta",{"property":"article:author","content":"Northword"}],["meta",{"property":"article:published_time","content":"2020-11-13T17:28:10.000Z"}],["meta",{"property":"article:modified_time","content":"2022-09-12T09:20:16.000Z"}],["script",{"type":"application/ld+json"},"{\\"@context\\":\\"https://schema.org\\",\\"@type\\":\\"Article\\",\\"headline\\":\\"numpy 在 win2004 及以上报错\\",\\"image\\":[\\"\\"],\\"datePublished\\":\\"2020-11-13T17:28:10.000Z\\",\\"dateModified\\":\\"2022-09-12T09:20:16.000Z\\",\\"author\\":[{\\"@type\\":\\"Person\\",\\"name\\":\\"Northword\\",\\"url\\":\\"https://northword.cn\\"}]}"]]},"headers":[],"git":{"createdTime":1662963508000,"updatedTime":1662974416000,"contributors":[{"name":"Northword","email":"northword@outlook.com","commits":3}]},"readingTime":{"minutes":1.18,"words":354},"filePathRelative":"dft-learning/09.Others/03.numpy-in-win20H2.md","localizedDate":"2020年11月14日","excerpt":"<h1> 在 Windows 20H2 上运行 ASE 报错</h1>\\n<div class=\\"language-powershell line-numbers-mode\\" data-ext=\\"powershell\\"><pre class=\\"language-powershell\\"><code> ase <span class=\\"token operator\\">--</span>version\\n <span class=\\"token operator\\">*</span><span class=\\"token operator\\">*</span> On entry to DGEBAL parameter number  3 had an illegal value\\n <span class=\\"token operator\\">*</span><span class=\\"token operator\\">*</span> On entry to DGEHRD  parameter number  2 had an illegal value\\n <span class=\\"token operator\\">*</span><span class=\\"token operator\\">*</span> On entry to DORGHR DORGQR parameter number  2 had an illegal value\\n <span class=\\"token operator\\">*</span><span class=\\"token operator\\">*</span> On entry to DHSEQR parameter number  4 had an illegal value\\nTraceback <span class=\\"token punctuation\\">(</span>most recent call last<span class=\\"token punctuation\\">)</span>:\\n  File <span class=\\"token string\\">\\"c:\\\\users\\\\northword\\\\appdata\\\\local\\\\programs\\\\python\\\\python39\\\\lib\\\\runpy.py\\"</span><span class=\\"token punctuation\\">,</span> line 197<span class=\\"token punctuation\\">,</span> in _run_module_as_main\\n    <span class=\\"token keyword\\">return</span> _run_code<span class=\\"token punctuation\\">(</span>code<span class=\\"token punctuation\\">,</span> main_globals<span class=\\"token punctuation\\">,</span> None<span class=\\"token punctuation\\">,</span>\\n  File <span class=\\"token string\\">\\"c:\\\\users\\\\northword\\\\appdata\\\\local\\\\programs\\\\python\\\\python39\\\\lib\\\\runpy.py\\"</span><span class=\\"token punctuation\\">,</span> line 87<span class=\\"token punctuation\\">,</span> in _run_code\\n    exec<span class=\\"token punctuation\\">(</span>code<span class=\\"token punctuation\\">,</span> run_globals<span class=\\"token punctuation\\">)</span>\\n  File <span class=\\"token string\\">\\"C:\\\\Users\\\\Northword\\\\AppData\\\\Roaming\\\\Python\\\\Python39\\\\Scripts\\\\ase.exe\\\\__main__.py\\"</span><span class=\\"token punctuation\\">,</span> line 4<span class=\\"token punctuation\\">,</span> in &lt;module&gt;\\n  File <span class=\\"token string\\">\\"C:\\\\Users\\\\Northword\\\\AppData\\\\Roaming\\\\Python\\\\Python39\\\\site-packages\\\\ase\\\\__init__.py\\"</span><span class=\\"token punctuation\\">,</span> line 8<span class=\\"token punctuation\\">,</span> in &lt;module&gt;\\n    import numpy as np\\n  File <span class=\\"token string\\">\\"C:\\\\Users\\\\Northword\\\\AppData\\\\Roaming\\\\Python\\\\Python39\\\\site-packages\\\\numpy\\\\__init__.py\\"</span><span class=\\"token punctuation\\">,</span> line 305<span class=\\"token punctuation\\">,</span> in &lt;module&gt;\\n    _win_os_check<span class=\\"token punctuation\\">(</span><span class=\\"token punctuation\\">)</span>\\n  File <span class=\\"token string\\">\\"C:\\\\Users\\\\Northword\\\\AppData\\\\Roaming\\\\Python\\\\Python39\\\\site-packages\\\\numpy\\\\__init__.py\\"</span><span class=\\"token punctuation\\">,</span> line 302<span class=\\"token punctuation\\">,</span> in _win_os_check\\n    raise RuntimeError<span class=\\"token punctuation\\">(</span>msg<span class=\\"token punctuation\\">.</span>format<span class=\\"token punctuation\\">(</span>__file__<span class=\\"token punctuation\\">)</span><span class=\\"token punctuation\\">)</span> <span class=\\"token keyword\\">from</span> None\\nRuntimeError: The current Numpy installation <span class=\\"token punctuation\\">(</span><span class=\\"token string\\">'C:\\\\\\\\Users\\\\\\\\Northword\\\\\\\\AppData\\\\\\\\Roaming\\\\\\\\Python\\\\\\\\Python39\\\\\\\\site-packages\\\\\\\\numpy\\\\\\\\__init__.py'</span><span class=\\"token punctuation\\">)</span> fails to pass a sanity check due to a bug in the windows runtime<span class=\\"token punctuation\\">.</span> See this issue <span class=\\"token keyword\\">for</span> more information: https:<span class=\\"token operator\\">/</span><span class=\\"token operator\\">/</span>tinyurl<span class=\\"token punctuation\\">.</span>com/y3dm3h86\\n</code></pre><div class=\\"line-numbers\\" aria-hidden=\\"true\\"><div class=\\"line-number\\"></div><div class=\\"line-number\\"></div><div class=\\"line-number\\"></div><div class=\\"line-number\\"></div><div class=\\"line-number\\"></div><div class=\\"line-number\\"></div><div class=\\"line-number\\"></div><div class=\\"line-number\\"></div><div class=\\"line-number\\"></div><div class=\\"line-number\\"></div><div class=\\"line-number\\"></div><div class=\\"line-number\\"></div><div class=\\"line-number\\"></div><div class=\\"line-number\\"></div><div class=\\"line-number\\"></div><div class=\\"line-number\\"></div><div class=\\"line-number\\"></div><div class=\\"line-number\\"></div></div></div>","autoDesc":true}`);export{n as data};
